### ISSUE TITLE
could this be installed on a shared Hosting environment such as Godaddy or Bluehost

### ISSUE THREAD

**Issue by rhinopctec** [MehaRima/online_ambulance_booking_service#7]
could this be installed on a shared Hosting environment such as Godaddy or Bluehost?

**Comment by MehaRima** [comment]
> could this be installed on a shared Hosting environment such as Godaddy or Bluehost?

Hello!!
First of all, I would like to request  you to go through the readme section as I have already mentioned there that it is a prototype and since it is made open source,you can always take the initiative to improve the accessibility of the project.
Thank you.
P.S:-
For requesting development works from the original creator , please respond with "Requesting Development Services" or create another thread with the same .
